from fastapi import APIRouter,Depends
from sqlalchemy.orm import Session
from app.schema.packaged_food_allergen_schema import PackageFoodAllergenSchema,UpdatePackageFoodAllergen,PackageFoodAllergenResponse
from app.service.package_food_allergen_service import PackageFoodAllergenService
from app.dependency.service_dependency import get_package_food_service