"""dev-ashu : TimeStamp add and user_status gender column add

Revision ID: 12b5bcdf9397
Revises: 440dd9a6b470
Create Date: 2026-09-11 17:21:29.631591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12b5bcdf9397'
down_revision: Union[str, Sequence[str], None] = '440dd9a6b470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create PostgreSQL ENUM types first
    gender_enum = sa.Enum(
        'MALE',
        'FEMALE',
        'OTHER',
        name='gender'
    )
    user_status_enum = sa.Enum(
        'ACTIVE',
        'INACTIVE',
        'SUSPENDED',
        name='user_status'
    )
    gender_enum.create(op.get_bind(), checkfirst=True)
    user_status_enum.create(op.get_bind(), checkfirst=True)
    # Add timestamp columns
    op.add_column(
        'user_device',
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=False
        )
    )
    op.add_column(
        'user_device',
        sa.Column(
            'updated_at',
            sa.DateTime(),
            nullable=False
        )
    )
    # Add enum columns
    op.add_column(
        'users',
        sa.Column(
            'gender',
            gender_enum,
            nullable=False
        )
    )
    op.add_column(
        'users',
        sa.Column(
            'user_status',
            user_status_enum,
            nullable=False
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_status')
    op.drop_column('users', 'gender')
    op.drop_column('user_device', 'updated_at')
    op.drop_column('user_device', 'created_at')
    user_status_enum = sa.Enum(
        'ACTIVE',
        'INACTIVE',
        'SUSPENDED',
        name='userstatus'
    )
    gender_enum = sa.Enum(
        'MALE',
        'FEMALE',
        'OTHER',
        name='gender'
    )

    user_status_enum.drop(op.get_bind(), checkfirst=True)
    gender_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
