"""dev-ashu : user device model complete

Revision ID: 440dd9a6b470
Revises: 8275a8160410
Create Date: 2026-09-11 17:15:12.061197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440dd9a6b470'
down_revision: Union[str, Sequence[str], None] = '8275a8160410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'brand', ['id'])
    op.add_column('user_device', sa.Column('device_type', sa.String(), nullable=False))
    op.add_column('user_device', sa.Column('firebase_fcm_token', sa.String(), nullable=False))
    op.add_column('user_device', sa.Column('last_login', sa.DateTime(), nullable=False))
    op.add_column('user_device', sa.Column('logout_time', sa.DateTime(), nullable=True))
    op.add_column('user_device', sa.Column('is_login', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_device', 'is_login')
    op.drop_column('user_device', 'logout_time')
    op.drop_column('user_device', 'last_login')
    op.drop_column('user_device', 'firebase_fcm_token')
    op.drop_column('user_device', 'device_type')
    op.drop_constraint(None, 'brand', type_='unique')
    # ### end Alembic commands ###
