"""dev-ashu : Allergen , PackageFoodAllergen , PackageFoodNutritent , Brand ,FoodCategory model added  and some update in usermodel

Revision ID: 8275a8160410
Revises: ab6a9eba123c
Create Date: 2026-09-10 18:28:37.238483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8275a8160410'
down_revision: Union[str, Sequence[str], None] = 'ab6a9eba123c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=220), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('brand',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=220), nullable=True),
    sa.Column('country_name', sa.String(length=220), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('food_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=220), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrient',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('nutrition_nutrient',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('nutrient_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['nutrient_id'], ['nutrient.id'], ),
    sa.ForeignKeyConstraint(['package_id'], ['package_food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_nutrient_nutrient_id'), 'nutrition_nutrient', ['nutrient_id'], unique=False)
    op.create_index(op.f('ix_nutrition_nutrient_package_id'), 'nutrition_nutrient', ['package_id'], unique=False)
    op.create_table('package_food_allergen',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_food_id', sa.Integer(), nullable=False),
    sa.Column('allergen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergen.id'], ),
    sa.ForeignKeyConstraint(['package_food_id'], ['package_food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_food_allergen_allergen_id'), 'package_food_allergen', ['allergen_id'], unique=False)
    op.create_index(op.f('ix_package_food_allergen_package_food_id'), 'package_food_allergen', ['package_food_id'], unique=False)
    op.add_column('package_food', sa.Column('brand_id', sa.Integer(), nullable=False))
    op.add_column('package_food', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.add_column('package_food', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('package_food', sa.Column('allergens_id', sa.Integer(), nullable=False))
    op.add_column('package_food', sa.Column('serving_size', sa.Float(), nullable=True))
    op.add_column('package_food', sa.Column('serving_unit', sa.String(length=20), nullable=True))
    op.add_column('package_food', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('package_food', sa.Column('quantity_unit', sa.String(length=20), nullable=True))
    op.add_column('package_food', sa.Column('food_claims', sa.String(length=225), nullable=True))
    op.alter_column('package_food', 'barcode',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('package_food', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_index(op.f('ix_package_food_brand_id'), 'package_food', ['brand_id'], unique=False)
    op.create_unique_constraint(None, 'package_food', ['barcode'])
    op.create_unique_constraint(None, 'package_food', ['image_url'])
    op.create_foreign_key(None, 'package_food', 'allergen', ['allergens_id'], ['id'])
    op.create_foreign_key(None, 'package_food', 'food_category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'package_food', 'brand', ['brand_id'], ['id'])
    op.drop_column('package_food', 'description')
    op.drop_column('package_food', 'name')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=225),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=225),
               nullable=False)
    op.drop_column('users', 'user_status')
    op.add_column('package_food', sa.Column('name', sa.VARCHAR(length=225), autoincrement=False, nullable=False))
    op.add_column('package_food', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'package_food', type_='foreignkey')
    op.drop_constraint(None, 'package_food', type_='foreignkey')
    op.drop_constraint(None, 'package_food', type_='foreignkey')
    op.drop_constraint(None, 'package_food', type_='unique')
    op.drop_constraint(None, 'package_food', type_='unique')
    op.drop_index(op.f('ix_package_food_brand_id'), table_name='package_food')
    op.alter_column('package_food', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('package_food', 'barcode',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('package_food', 'food_claims')
    op.drop_column('package_food', 'quantity_unit')
    op.drop_column('package_food', 'quantity')
    op.drop_column('package_food', 'serving_unit')
    op.drop_column('package_food', 'serving_size')
    op.drop_column('package_food', 'allergens_id')
    op.drop_column('package_food', 'category_id')
    op.drop_column('package_food', 'image_url')
    op.drop_column('package_food', 'brand_id')
    op.drop_index(op.f('ix_package_food_allergen_package_food_id'), table_name='package_food_allergen')
    op.drop_index(op.f('ix_package_food_allergen_allergen_id'), table_name='package_food_allergen')
    op.drop_table('package_food_allergen')
    op.drop_index(op.f('ix_nutrition_nutrient_package_id'), table_name='nutrition_nutrient')
    op.drop_index(op.f('ix_nutrition_nutrient_nutrient_id'), table_name='nutrition_nutrient')
    op.drop_table('nutrition_nutrient')
    op.drop_table('nutrient')
    op.drop_table('food_category')
    op.drop_table('brand')
    op.drop_table('allergen')
    # ### end Alembic commands ###
