"""dev-priti : add gender and user status in user table

Revision ID: ab6a9eba123c
Revises: 6c82e16bf7c8
Create Date: 2026-09-09 16:39:13.016083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab6a9eba123c'
down_revision: Union[str, Sequence[str], None] = '6c82e16bf7c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('package_food', sa.Column('barcode', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user_device', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_device', type_='unique')
    op.drop_column('package_food', 'barcode')
    # ### end Alembic commands ###
